# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    variables:
       tags: $(Build.BuildId)

    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)'
        tags: |
          $(Build.BuildId)
          


    - task: CopyFiles@2
      inputs:
        Contents: 'eks-deploy-from-ecr.yaml'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'defaultservcon'
        azureContainerRegistry: '{"loginServer":"acr2245.azurecr.io", "id" : "/subscriptions/4d26045c-f819-4042-9134-8e22c0ce079e/resourceGroups/sys/providers/Microsoft.ContainerRegistry/registries/acr2245"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'

